# XGBoost Model Parameters

# Core Parameters
objective: "binary:logistic"
eval_metric: "auc"
n_estimators: 100

# Tree Booster Parameters
learning_rate: 0.1
max_depth: 3
min_child_weight: 1
gamma: 0.0

# Sampling Parameters
subsample: 0.8
colsample_bytree: 0.8

# Regularization Parameters
reg_alpha: 0.0  # L1 regularization
reg_lambda: 1.0  # L2 regularization

# Class Imbalance Parameters
scale_pos_weight: 1.0

min_child_weight: 0